name: windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - name: Download vim
        shell: PowerShell
        run: Invoke-WebRequest -Uri https://github.com/vim/vim-win32-installer/releases/download/v8.2.0037/gvim_8.2.0037_x64.zip -OutFile vim.zip
      - name: Extract vim
        shell: PowerShell
        run: Expand-Archive -Path vim.zip -DestinationPath $env:USERPROFILE
      - name: Download test runner
        shell: cmd
        run: git clone --depth 1 --branch v1.5.4 --config core.autocrlf=false --single-branch https://github.com/thinca/vim-themis $USERPROFILE/themis
      - name: Run tests
        shell: cmd
        run: |
          SET PATH=%USERPROFILE%\vim\vim82;%PATH%;
          SET PATH=%USERPROFILE%\themis\bin;%PATH%;
          vim --version
          themis --reporter spec
