name: windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - name: Download vim
        shell: PowerShell
        run: Invoke-WebRequest -Uri https://github.com/vim/vim-win32-installer/releases/download/v8.2.0035/gvim_8.2.0035_x64.zip -OutFile vim.zip
      - name: Extract vim
        shell: PowerShell
        run: Expand-Archive -Path vim.zip -DestinationPath $env:USERPROFILE
      - name: Download test runner
        shell: cmd
        run: |
          git config --global core.autocrlf true
          git clone --depth 1 --branch v1.5.4 --single-branch https://github.com/thinca/vim-themis %USERPROFILE%\themis
      - name: Set PATH
        shell: cmd
        run: SET PATH=%USERPROFILE%\vim\vim82;%PATH%
      - name: Show versions
        shell: cmd
        run: vim --version
      - name: Run tests
        shell: cmd
        run: %USERPROFILE%\themis\bin\themis.bat --reporter spec

